# =============================================================================
# Management Network Configuration (管理用ネットワーク)
# =============================================================================
MGT_IF="ens3"
MGT_IP="172.31.220.85/23"
MGT_GW="172.31.220.1"

SYSTEM_DNS="172.31.100.21 172.31.100.100 172.31.100.20"
SYSTEM_NTP="172.31.100.21 172.31.100.100 172.31.100.20"
DOMAIN="my.corp"

# IPv6 アドレスの省略記法 :: は変数の後ろには置かない
# PREFIX では省略記法を使わず :0: とする
# =============================================================================
# WAN & MAP-E Network Configuration
# =============================================================================
MAPE_IF="ens8"
# それぞれの方式で使う VLAN番号をスペース区切りで指定する
# 不要な場合は空にしておく
SLAAC_DYN_VLANS="841 842 843 844"
PD_DYN_VLANS="845 846 947 948"
SLAAC_FIX_VLANS="849"
PD_FIX_VLANS="850"

BR_IF=dummy0
PROV_IF=dummy1

# 基幹IPv6プレフィックス (末尾にコロンは含めない)
#BASE_SUBNET="5f00:3aa"
BASE_SUBNET="2400:4150"

# =============================================================================
# 6. MAP-E (OCN Virtual Connect) Parameters
# =============================================================================
# 🌟 OCN仕様: BRのIPv6は、BR_PREFIX(5f00:3aa:a001)の末尾に、
# BR_IPV4_ADDR(100.127.255.255 -> 647f:ffff) を埋め込んだアドレスを構成
BR_PREFIX="${BASE_SUBNET}:3220"
BR_IPV4_ADDR="100.127.255.255"
# BR_IPV6 : 自動生成

# 動的 IPv4 クライアント(CE)へ払い出すIPv4プールセグメント
# この /16 内から、各CEへランダムに /32 を引き当てて散らばりを持たせる
# BR_IPV4_POOL="198.51.0.0"
BR_IPV4_POOL="1.1.0.0"
BR_IPV4_MASK="16"

# プロビジョニング用ネットワーク (DNS, NTP, provisioning server)
# --- 5. Services (DNS/NTP) on WAN ---
MAPE_PROV_PREFIX="${BASE_SUBNET}:9999"
MAPE_DNS_IP="${MAPE_PROV_PREFIX}::53"
MAPE_NTP_IP="${MAPE_PROV_PREFIX}::123"
MAPE_PROV_IP="${MAPE_PROV_PREFIX}::ff"
MAPE_DOMAIN_SEARCH="map.ocn.ad.jp"

# --- 1. ひかり電話無し動的 IPv4 SLAAC WAN ---
# SLAACで BR-CE 間の物理セグメント
# 各 vlan は　SLAAC_BR_PREFIX に vlan 番号を足す
# ${BASE_SUBNET}:${SLAAC_BR_BASE}::${SLAAC_BR_SUFFIX}
SLAAC_BR_BASE="1000"
SLAAC_BR_SUFFIX="::ff0a"

# --- 2. ひかり電話あり動的 IPv4 DHCPv6-PD ---
# CEへの委譲用プレフィックスプール 
PD_POOL="2000"

# --- 3. ひかり電話なし固定IP SLAAC ---
# SLAACで使用する物理セグメント
SLAAC_FIX_BR_PREFIX="3000"
SLAAC_FIX_BR_SUFFIX="::ff0d"

# --- 4. ひかり電話あり・固定 IPv4 (DHCPv6-PD固定) ---
PD_FIX_POOL="4000"
