# PPPoE User Configuration
# Format: Username Password Client_IP_or_Subnet Service_Name Note
ab4t-ash@atson.net             asahi          10.6.0.1/29          asahi-net    asahi net サンプル
hi/abc12345@bf.hi-ho.ne.jp     hi-ho          10.7.0.1/27          hi-ho        hi-ho サンプル
user-ocn@one.ocn.ne.jp         ocn            *                    OCN          OCN サンプル
user01-RTX@vpn002              pass01         10.1.0.1             VPN_Gr2      VPN_Gr2-RTX
user01-IX@vpn001               pass01         10.0.0.1             VPN_Gr1      VPN_Gr1_IX-router
