# /etc/logrotate.d/syslog-ng
# AxoSyslog 内で実行されるログローテーション設定 (1日1回・20世代保持・一般ユーザー権限0666)

/var/log/messages
/var/log/errors.log
/var/log/docker-stdout.log
/var/log/pppoe-server.log
/var/log/mape-provisioning-server.log
/var/log/mape-route-monitor.log
/var/log/mape-tunnel-events.log
/var/log/radvd.log
/var/log/chrony.log
/var/log/bind.log
/var/log/web-dashboard-access.log
/var/log/kea/*.log
{
    su root root
    daily
    rotate 20
    missingok
    notifempty
    nocompress
    create 0666 root root
    sharedscripts
    postrotate
        /usr/sbin/syslog-ng-ctl reopen >/dev/null 2>&1 || true
    endscript
}
